[package]
name = "elcord-rs"
authors = ["TheLinuxPirate"]
version = "0.0.0"
edition = "2021"

[dependencies]
emacs = "0.18.0"
xcb = "1.3.0"
xcb-util = { version = "0.4.0", features = ["ewmh"] }
x11rb = "0.13.0"

[lib]
crate-type = ["cdylib"]